### ISSUE TITLE
"invalid index" error with Float64 key when names type is not Float64

### ISSUE THREAD

**Issue by nalimilan** [davidavdav/NamedArrays.jl#62] opened 2018-04-10 12:15 UTC
When the type of the names is not `Float64` (e.g. `Any`) but some keys are `Float64`, indexing does not work. Interestingly, passing the same key as an integer works.

```julia
julia> x=NamedArray([1,2,3], ([1.0,"a",2.0],))
3-element Named Array{Int64,1}
A   │ 
────┼──
1.0 │ 1
a   │ 2
2.0 │ 3

julia> x[1.0]
ERROR: ArgumentError: invalid index: 1.0
Stacktrace:
 [1] getindex(::NamedArrays.NamedArray{Int64,1,Array{Int64,1},Tuple{DataStructures.OrderedDict{Any,Int64}}}, ::Float64) at /home/milan/.julia/NamedArrays/src/index.jl:31
 [2] macro expansion at ./REPL.jl:97 [inlined]
 [3] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73

julia> x["a"]
2

julia> x[1]
1

```

This affects FreqTables with `Union{Float64,Missing}` variables (https://github.com/nalimilan/FreqTables.jl/issues/23).

**Comment by davidavdav** [comment] 2018-04-10 20:08
I can see where the problem comes from, I think.  The dictionary lookup is dispatched by recognizing the keytype.  Here this type is Any, but the float is not Any, and probably another dispatch route takes precedence (there is a dispatch on Real, I think, which maps to to_index() ).

I don't see an easy solution, maybe you can wrap the indices in a type that includes the Float64 and Missing, and use that wrapper in indexing as well.

**Comment by nalimilan** [comment] 2018-04-10 20:14
Yet it works with `1`, which isn't of the type of names at all. So there must be a way to make `1.0` work too.

**Comment by davidavdav** [comment] 2018-04-20 07:05
Index `1` works, because it is the first index.  `2.0` can be indexed using `3` for the same reason. 

I have to keep NamedArrays indexable by plain integers just like underlying Array.  

The only exception in the current design is when in defining the NamedArray the keys are integers themselves, in that case the index type is recognized as a key (and not an integer index) by its type. 

But I'll see if I can somehow find a fix for this issue.

**Comment by nalimilan** [comment] 2018-04-20 07:15
Funny, I hadn't tried other values. Anyway the `x[1]` example isn't really related, I just found it surprising that it worked.

**Comment by davidavdav** [comment] 2018-04-20 08:08
I am currently confused why
```julia
struct Mixed
       x
end
d = Dict{Mixed, Int}(Mixed(1.0) => 1, Mixed("a") => 2, Mixed(3) => 3)
d[Mixed("a")]
ERROR: KeyError: key Mixed("a") not found
Stacktrace:
 [1] getindex(::Dict{Mixed,Int64}, ::Mixed) at ./dict.jl:474
```
Somehow various `Mixed` instances are not the same.

**Comment by davidavdav** [comment] 2018-04-20 12:48
OK, great, 

so with such a type definition `Mixed` used as a wrapper to deal with heterogeneous types in both the namedarray definition and usage, this should solve this issue:
```julia
struct Mixed x end
Base.hash(x::Mixed, h::UInt) = hash(x.x, h) ## version 0.6
Base.:(==)(x::Mixed, y::Mixed) = x.x == y.x ## version 0.6
Base.show(io::IO, m::Mixed) = show(io, m.x)

n = NamedArray([1,2,3], (Mixed.([1.0,"a",2.0]),))
3-element Named Array{Int64,1}
A   │ 
────┼──
1.0 │ 1
"a" │ 2
2.0 │ 3

n[Mixed(1.0)]
1
n[Mixed(2.0)]
3
```

But I am not entirely sure if this is the kind of solution you were looking for.

**Comment by nalimilan** [comment] 2018-04-20 12:57
That doesn't sound very satisfying indeed, as FreqTable users wouldn't expect to have to deal with the `Mixed` wrapper type. There must be a way to fix this internally.

**Comment by davidavdav** [comment] 2018-06-04 09:26
Hi, 

I am sorry, but I have been having a 2-line fix around https://github.com/davidavdav/NamedArrays.jl/tree/fix-62 that at least works for the above case, I think.  I was also busy in another branch taking an entirely different approach for reasons that I can now no longer understand. 

In this fix, normal indexing (`x[2]`) will not give the second element, so I am not so happy with that.  So the tests are not passed. 

So could one of you assess if this fix solves your issues, or at least partly?

**Comment by nalimilan** [comment] 2018-06-04 10:31
Yes, that fixes the problem, but indeed the fact that `x[2]` doesn't return the second element isn't really acceptable. So we need a different approach which doesn't affect integer indexing.

The case of floating point indices is problematic anyway: `1.0 == 1`, so it would make sense to treat them the same. On the other hand, indexing `Array` with floats isn't supported in Base, so it wouldn't be absurd to throw an error either. Finally, it could be used to access the element with name `1.0`, but that could be confusing. I think we really need a `Name` type which would allow specifying that a value should be interpreted as a name even if it's a `Number` or `Integer`.

**Comment by davidavdav** [comment] 2018-06-04 10:42
You _can_ already use integers or floating points as indices for NamedArrays now, but only if all of them are of the same type.  The problem arises from the mixed type of the index at construction time.  

I would treat `1` differently from `1.0` as index.

**Comment by bkamins** [comment] 2018-06-04 20:10
You know the details of the package better, but I would recommend to disallow setting `<:Integer` as column level name and explicitly check for this (this would disallow also `Bool` as index in particular which is also problematic).

Here is just one example why this is bad:
```
julia> x = NamedArray([1,2], ( [Int32(2),Int32(1)],), ("ROWS",))
2-element Named Array{Int64,1}
ROWS  │
──────┼──
2     │ 1
1     │ 2

julia> x[1]
1

julia> x[Int32(1)]
2
```
This is under Julia built for 64-bit target. This code would produce a different result on Julia built for 32-bit target (so the behavior of the code would be platform dependent which is very bad).

Given that we agreed this would be disallowed I would recommend the following design:
Use the recommendation of @nalimilan and create some thin wrapper that would be always used internally to store names of dimension levels. Tentatively let us call it `Name` (probably a better name is needed). Now `NamedArray` could automatically wrap everything that is passed as level name in dimension (so e.g. FreqTables does not have to care about it). Now the crucial part is that when the object is created and we want to access it the following rules could be used:
    * if `<:Integer` is passed - use standard indexing from `Base`;
    * if `Name{T}(something)` is passed - use indexing using level name;
    * if the two rules above are not met - wrap `something` into `Name{T}` and use indexing using level name;
In this way for almost all cases there is no visible change for the user. All works as in the past. The only difference is when we created the level names using e.g. integers (which still can be done normally) - then we have to access them using a wrapper type.

The type should be defined as:
```
struct Name{T}
    val::T
end
```
to ensure it is fast (pretty much the definition is the same as `Some` in Julia 0.7).

**Comment by bkamins** [comment] 2018-06-04 20:29
Additionally we should handle `Colon` in the same way as `<:Integer`, here is a corner case (unlikely of course):

```
julia> x = NamedArray([1,2], ( [Colon(),"abc"],), ("ROWS",))
2-element Named Array{Int64,1}
ROWS    │
────────┼──
Colon() │ 1
abc     │ 2

julia> x[Colon()]
2-element Named Array{Int64,1}
ROWS    │
────────┼──
Colon() │ 1
abc     │ 2
```

**Comment by davidavdav** [comment] 2018-06-05 22:16
I think we'd have to allow `<:Integer` as index, with indeed the behaviour you sketch.   Think of a frequency table of a set of integers, there, the indices are integer.  

The internals of NamedArrays should be robust against such usage, I'm not sure if they are everywhere, but I think I have a small section in testing named "dodgy indices" to test this.  

I think code not always behaves the same on 32 and 64 bit targets, e.g., with `Int` arithmetics.  If you use integers as index to a NamedArray, and then use a different type of integer for indexing, then your asking for trouble...

**Comment by bkamins** [comment] 2018-06-06 10:57
I know that this was an obscure and extreme example, but the problem I have in general is that `NamedArray` is a subtype of `AbstractArray` and for instance the following code fails:

```
julia> x = NamedArray([100,200], ( [2,3],), ("ROWS",))
2-element Named Array{Int64,1}
ROWS  │
──────┼────
2     │ 100
3     │ 200

julia> [x[i] for i in eachindex(x)]
ERROR: KeyError: key 1 not found
Stacktrace:
 [1] getindex at D:\Software\JULIA_PKG\v0.6\DataStructures\src\ordered_dict.jl:361 [inlined]
 [2] indices(::DataStructures.OrderedDict{Int64,Int64}, ::Int64) at D:\Software\JULIA_PKG\v0.6\NamedArrays\src\index.jl:39
 [3] getindex(::NamedArrays.NamedArray{Int64,1,Array{Int64,1},Tuple{DataStructures.OrderedDict{Int64,Int64}}}, ::Int64) at D:\Software\JULIA_PKG\v0.6\NamedArrays\src\index.jl:31
 [4] collect(::Base.Generator{Base.OneTo{Int64},##1#2}) at .\array.jl:470
```

This is not a huge problem if you are working in interactive environment, but if you would use `NamedArray` as a building block of something bigger (e.g. in other packages) you cannot be sure where `NamedArray` would be passed and how it would be used so if it does not strictly follow `AbstractArray` interface it might cause issues.

And of course the decision is still to be made if `<:Integer` keys are wrapped in a collection of a more general type.

Anyway - I guess that I would recommend that given the issues I have raised you make a decision where to go with `NamedArrays` design as long as it will be well documented 😄. Thank you!

**Comment by davidavdav** [comment] 2018-06-06 11:32
I would have to study to understand what `eachindex` gives.  For one thing, I might have to overload `eachindex(::NamedArray)`.  It should, of course, work.

**Comment by bkamins** [comment] 2018-06-06 12:50
What would be great to have is if `NamedArray` followed `AbstractArray` interface as defined here https://docs.julialang.org/en/latest/manual/interfaces/#man-interface-array-1 (here probably `IndexStyle` is an important decision that differentiates the current approach from what I have described above).

As I have said - in order to move forward I think anything you decide to do is OK for me as long as it is documented and the problem with an integer wrapped in a more general container is solved. A great benefit would be if it were 100% compliant with `AbstractArray` interface. Of course I would gladly test whatever design you decide to choose.

**Comment by davidavdav** [comment] 2018-06-06 12:53
If `eachindex(::AbstractVector)` would just give a `CartesianIndex{1}()` it would have worked.  But it gives and `Int`. 

It is great to have all these examples to break NamedArrays, with these I can make NamedArrays more robust.  Hopefully in a more structured way, rather than on an ad-hoc basis. 

In another (local) branch I was trying to mimic the logic of `to_indices` of Base to solve the original issue.  But that remains unfinished work as well.

**Comment by davidavdav** [comment] 2018-06-06 12:56
Thanks for that link.  I think NamedArrays should be implementing that interface.  When I started NamedArrays, I don't believe that info was out there.

**Comment by nalimilan** [comment] 2018-06-07 13:22
IIUC the idea currently is to have `Integer` indices behave as for `Array`, i.e. treat them as 1-based linear indices. That plays well with `eachindex` returning a range as for `Array`. It's good since `eachindex` is supposed to return an efficient iterator over an array.

**Comment by davidavdav** [comment] 2018-06-08 07:55
@nalimilan Are you proposing the standard Integer interpretation for the index should have precedence over `Integer` named keys, meaning you can't use integers as dict keys unless you manually wrap them?

**Comment by nalimilan** [comment] 2018-06-08 10:03
> @nalimilan Are you proposing the standard Integer interpretation for the index should have precedence over Integer named keys, meaning you can't use integers as dict keys unless you manually wrap them?

Yes. Anyway when you have integer names there's an ambiguity. @bkamins and I suggest it makes sense to resolve it in favor of the standard `AbstractArray` indexing rules so that `NamedArray` objects can be used with all functions which accept `AbstractArray` objects, even when they don't know about `NamedArray`. Else things could break unexpectedly for some functions, or could even silently give incorrect results.

**Comment by davidavdav** [comment] 2018-06-08 10:40
OK, great, this would simplify things for me.  But this also has as a consequence that FreqTable should wrap indices in case the objects happen to be of type `Integer`.  Earlier this was considered not ideal, in the case of a mixed type index.  

Suppose I have 
```
n = NamedArray([1,2,3], ([1.0,"a",2],))
```
what should be the value of `n[2]` according to you?  

I believe the value should be `2` according to the `AbstractArray` rules.  This would require to use a wrapper like `n[Name(2)]` to access the value `3`, which is kind of defeating the purpose of `NamedArrays`, but alas, maybe the key types should have be chosen differently.

**Comment by bkamins** [comment] 2018-06-08 12:55
This is what I would suggest. The issue is what wrapper type to use. Also as I have said earlier - actually you do not have to pass a wrapper type when creating a `NamedArray` (constructor can to it by default). It would be only needed to access '<:Integer` dictionary keys. Also I would allow to access by a wrapper always as an option (for any type dict key) as then again - a packages can be safely developed to access `NamedArray` index via a wrapper (of course for non-integer keys this would be optional).

Notice that in R `table` behaves in exactly identical fashion as is proposed here:
```
> x = table(sample(2:10, 100, replace=T))
> x

 2  3  4  5  6  7  8  9 10 
11  9 17 13 13 11 10  5 11 
> x[1]
 2 
11 
> x[2]
3 
9 
> x["2"]
 2 
11 
```

The only issue is what should be the name of the wrapper type as `Name` seems a bit to common (but @nalimilan has more experience with naming than me so maybe this is OK)?

**Comment by davidavdav** [comment] 2018-06-09 11:09
In R names are always strings, so that is easy (although it has caused me a lot of trouble at the time, and I never use pure numeric strings as name to avoid confusion for myself).  At the very early stages in development I was urged not to assume anything about the key type, so quite some effort went into that.

**Comment by bkamins** [comment] 2018-06-09 11:19
I could see this 👍. And that is why I say that it is up to you to decide how you want to go forward. I am a package user reporting what issues I see.

My example with R was exactly meant to show that in R design on purpose only strings were allowed as names to avoid problems like we discuss here (like in DataFrames.jl we only allow `Symbol` as column name). Of course you can have much more flexibility in Julia than in R.

**Comment by nalimilan** [comment] 2018-06-09 15:20
> Earlier this was considered not ideal, in the case of a mixed type index.
> 
> Suppose I have
> 
> n = NamedArray([1,2,3], ([1.0,"a",2],))
> 
> what should be the value of n[2] according to you?
> 
> I believe the value should be 2 according to the AbstractArray rules. This would require to use a wrapper like n[Name(2)] to access the value 3, which is kind of defeating the purpose of NamedArrays, but alas, maybe the key types should have be chosen differently.

That sounds fine to me. My objection to the `Mixed` suggestion you made above was that I think it should only be required for integer names, but not in other situations. Maybe I didn't understand what you mean then.

> The only issue is what should be the name of the wrapper type as Name seems a bit too common (but @nalimilan has more experience with naming than me so maybe this is OK)?

`Name` doesn't sound too bad to me, given that the package is called NamedArrays. There's a risk of conflicts with other packages, but AFAICT no essential package uses that name currently so it's not unreasonable to claim it.

**Comment by davidavdav** [comment] 2018-06-10 10:32
We already have `Not` claimed as well (if I recall correctly that was a suggestion of @nalimilan), for a similar purpose.  Maybe this can be combined into a `Name(key, sense::Boolean=true)`.

**Comment by nalimilan** [comment] 2018-06-10 12:37
I hope `Not` will be included in Base at some point, and it can work with indices, not only names, so I'd say we'd better keep these distinct.

**Comment by davidavdav** [comment] 2018-06-13 08:16
Hello @nalimilan and @bkamins,  

Could you please have a look at branch [Abstract-interface](https://github.com/davidavdav/NamedArrays.jl/tree/Abstract-interface), where I took a dig at implementing the AbstractArray interface.  I have a feeling that this could potentially simplify the code quite a bit---I already noticed I could remove some ambiguity-resolving code. 

The idea is that now an `<:Integer` index always takes precedence as normal AbstractArray indexing, and that if you happen to have `<:Integer` keys in NamedArrays, you can escape these with `Name()`, just like earlier you could use `Not` to reverse an index.  `Not` seems to work transparantly mixed with `Name`, but I have not tested this thoroughly yet. 

Thanks

**Comment by nalimilan** [comment] 2018-06-13 11:59
Thanks! Based on a quick testing, it looks good!

FWIW, I don't think you really need to store the indexing style as an additional type parameter, as it can already be determined from the wrapped array type. You can just call `IndexStyle` on that type when needed.

**Comment by davidavdav** [comment] 2018-06-13 12:27
According to the interface definition I need to implement `getindex(A, i::Int)` if `IndexLinear` and `getindex(A, I::Vararg{Int, N})` if `IndexCartesian`.  Since I don't know what index type `A` is going to be, I figured I need to have the implementation depend on the indextype.

**Comment by nalimilan** [comment] 2018-06-13 12:41
I don't think it's a problem to define additional methods even when the interface doesn't require it. Only the relevant methods will be called. In Julia, one rarely (or never) tests whether a method is actually implemented before calling it: only traits determine what method is called.

**Comment by bkamins** [comment] 2018-06-13 12:55
I have added comments to the branch.

**Comment by davidavdav** [comment] 2018-06-18 10:43
I've updated the [README](https://github.com/davidavdav/NamedArrays.jl/blob/Abstract-interface/README.md) of the Abstract-interface branch, up to the section "General functions" which still is a bit old.  If you are happy with this definition of the functionality, and if this solves the original issue, I can merge and publish.

**Comment by nalimilan** [comment] 2018-06-19 07:50
Thanks! This looks good to me.

Indeed the indexing code has been reworked a lot in Base over the recent releases, so it may be possible to simplify the `NamedArray` implementation more than a few releases back.

**Comment by davidavdav** [comment] 2018-06-21 09:43
I've merged this to master, after updating the README a little more, and sent a PR to Metadata.

**Closed by davidavdav** 2018-06-21 09:43 UTC

**Comment by bkamins** [comment] 2018-06-21 15:02
Fantastic. Thank you!
