### ISSUE TITLE
Key returned instead of val when key is Integer

### ISSUE THREAD

**Issue by mcmcgrath13** [davidavdav/NamedArrays.jl#71] opened 2018-08-30 02:35 UTC
Got a BoundsError when one of the dims was an Integer, this seems to be because instead of returning the index, `indices(d,i)` returned the key.  It looks like it's hitting line 68 of index.jl instead of a different `indices` method.  I was able to workaround this by converting the integer dimension to string (as it is functionally categorical data), but the behavior was unexpected.

**Comment by davidavdav** [comment] 2018-08-30 07:54
Hi, do you know what version this was in?  We've been working on integer indexing recently.  It looks like we are going for the abstract array interface, where integer indexing always has precedence over key indexing, in cases where the key is of type integer.

**Comment by mcmcgrath13** [comment] 2018-08-30 12:38
This was on master.  Would it make sense to do a check if the key type is integer? E.g. `max(keys) > length(arr)`

**Comment by diegozea** [comment] 2018-08-30 12:45
When keys are integers you can use `Name(i)` rather than `i` to make sure that you're asking for the name/key `i`.

**Comment by nalimilan** [comment] 2018-09-02 13:53
Can you post a reproducible example?

**Comment by mcmcgrath13** [comment] 2018-09-04 20:47
@nalimilan I got this error using FreqTables, so the example there is:

```
using FreqTables
using DataFrames
df = DataFrame(A = 101:110, B = ["x","y","z"][rand(1:3, 10)])
ft = freqtable(df, :A, :B)
```

Looking into the FreqTables code, it looks like it constructs an all zeros NamedArray then when trying to access the NamedArray via the dim names, gets a BoundsError

```
a = zeros(Int64, 10, 3)
dimnms = [[101, 102, 103, 104, 105, 106, 107, 108, 109, 110], ["x", "y", "z"]]
vt = vectypes(Tuple{Int64,String})
dims = ("Dim1","Dim2")
na = NamedArray(a, tuple(dimnms...)::vt, dims)

# this is actually a for loop through a dictionary of indices and values, 
# but for simplicity I just included one iteration of the loop
na[(101, "x")...] = 1
```

This used to work without the string workaround, is this a change to the API that requires a change to FreqTables (perhaps using `Name(i)`)? Or should NamedArrays handle this as it used to?

**Comment by mcmcgrath13** [comment] 2018-09-05 12:48
@nalimilan excellent!  I just opened a [PR](https://github.com/nalimilan/FreqTables.jl/pull/29) on FreqTables to add an example to the README.

**Comment by davidavdav** [comment] 2020-02-19 09:23
Closing, as this all seems to have been resolved

**Closed by davidavdav** 2020-02-19 09:23 UTC
